version: '3.8'

services:
  api:
    build: .
    container_name: jnr-api-calculos
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_KEY: ${API_KEY}
      NODE_ENV: production
    networks:
      - jnr-network
    restart: unless-stopped

networks:
  jnr-network:
    name: jnr-network
    external: true